services:

  notes1:
    build: ../services/notes-service
    container_name: notes1
    ports:
      - "4001:4000"
    environment:
      - PORT=4000
    networks:
      - infra-net

  notes2:
    build: ../services/notes-service
    container_name: notes2
    ports:
      - "4002:4000"
    environment:
      - PORT=4000
    networks:
      - infra-net

  frontend:
    build: ../frontend
    container_name: frontend_prod
    ports:
      - "5173:80"
    networks:
      - infra-net
    depends_on:
      - notes1
      - notes2

  nginx:
    image: nginx:alpine
    container_name: nginx_lb
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - notes1
      - notes2
      - frontend
    networks:
      - infra-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - infra-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - infra-net

networks:
  infra-net:
    driver: bridge
