global:
  scrape_interval: 5s

scrape_configs:

  - job_name: 'notes-services'
    metrics_path: /metrics
    static_configs:
      - targets: ['notes1:4000', 'notes2:4000']
        labels:
          group: notes

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
